"""
Code Generator - Generates stub and skeleton code from IDL

Converts parsed IDL definitions into Python stub (client) and
skeleton (server) implementations.
"""

import os
from typing import Dict, List
from rpc_framework.idl.parser import IDLParser, Service, Method
from rpc_framework.utils import setup_logger

logger = setup_logger(__name__)


TYPE_MAPPING = {
    'int': 'int',
    'string': 'str',
    'float': 'float',
    'bool': 'bool',
    'list': 'list'
}


class CodeGenerator:
    """
    Generates Python RPC code from IDL definitions.
    
    Produces:
    - Stub (client proxy) classes
    - Skeleton (server dispatcher) classes
    """

    def __init__(self, parser: IDLParser):
        """
        Initialize code generator with parsed IDL.
        
        Args:
            parser: IDLParser with parsed services
        """
        self.parser = parser

    def generate_stub(self, service: Service, module_name: str = "generated") -> str:
        """
        Generate stub (client) code for a service.
        
        Args:
            service: Service definition
            module_name: Python module name for imports
            
        Returns:
            Generated Python code as string
        """
        code_lines = [
            '"""',
            f'Auto-generated RPC stub for {service.name} service',
            'DO NOT EDIT - Generated by RPC framework',
            '"""',
            '',
            'from typing import Any, List, Type',
            'from rpc_framework.transport.tcp_client import TCPClient',
            'from rpc_framework.runtime.stub import RPCStub',
            '',
            f'class {service.name}Stub:',
            '    """',
            f'    RPC Stub for {service.name} service.',
            '    """',
            '',
            '    def __init__(self, host: str = "127.0.0.1", port: int = 5000):',
            '        """Initialize stub with TCP client connection."""',
            '        self.client = TCPClient(host, port)',
            '        self.client.connect()',
            f'        self.stub = RPCStub(self.client, "{service.name}")',
            '',
        ]

        # Generate method proxies
        for method in service.methods:
            code_lines.extend(self._generate_method_stub(method))

        code_lines.extend([
            '',
            '    def close(self):',
            '        """Close connection to server."""',
            '        self.client.disconnect()',
        ])

        return '\n'.join(code_lines)

    def _generate_method_stub(self, method: Method) -> List[str]:
        """Generate a stub method proxy."""
        python_return_type = TYPE_MAPPING.get(method.return_type, method.return_type)
        
        # Build parameter list
        param_list = ', '.join([f"{pname}: {TYPE_MAPPING.get(ptype, ptype)}" 
                                for ptype, pname in method.params])
        param_names = ', '.join([pname for _, pname in method.params])

        if param_list:
            method_def = f"    def {method.name}(self, {param_list}) -> {python_return_type}:"
        else:
            method_def = f"    def {method.name}(self) -> {python_return_type}:"

        lines = [
            '',
            method_def,
            f'        """',
            f'        Call remote {method.name} method.',
            f'        """',
        ]

        if param_names:
            lines.append(f'        return self.stub.invoke("{method.name}", [{param_names}], {python_return_type})')
        else:
            lines.append(f'        return self.stub.invoke("{method.name}", [], {python_return_type})')

        return lines

    def generate_skeleton(self, service: Service) -> str:
        """
        Generate skeleton (server) code for a service.
        
        Args:
            service: Service definition
            
        Returns:
            Generated Python code as string
        """
        code_lines = [
            '"""',
            f'Auto-generated RPC skeleton for {service.name} service',
            'DO NOT EDIT - Generated by RPC framework',
            '"""',
            '',
            'from typing import Dict, Callable, List, Type',
            'from rpc_framework.runtime.skeleton import RPCSkeleton',
            'from rpc_framework.runtime.registry import ServiceRegistry',
            '',
            f'def create_{service.name.lower()}_skeleton(',
            f'    implementation: Any',
            ') -> RPCSkeleton:',
            '    """',
            f'    Create skeleton dispatcher for {service.name} service.',
            '    Args:',
            '        implementation: Instance of service implementation',
            '    Returns:',
            '        Configured RPCSkeleton',
            '    """',
            '    registry = ServiceRegistry()',
            '',
            '    # Register methods',
            f'    methods = {{',
        ]

        # Register methods
        for method in service.methods:
            code_lines.append(f'        "{method.name}": implementation.{method.name},')

        code_lines.extend([
            '    }',
            '',
            '    # Register parameter signatures for type validation',
            '    signatures = {',
        ])

        for method in service.methods:
            if method.params:
                param_types = ', '.join([f'{TYPE_MAPPING.get(ptype, ptype)}'
                                        for ptype, _ in method.params])
                code_lines.append(f'        "{method.name}": [{param_types}],')
            else:
                code_lines.append(f'        "{method.name}": [],')

        code_lines.extend([
            '    }',
            '',
            f'    registry.register_service("{service.name}", implementation, methods, signatures)',
            '    return RPCSkeleton(registry)',
        ])

        return '\n'.join(code_lines)

    def generate_all(self, output_dir: str = ".") -> Dict[str, str]:
        """
        Generate all code files.
        
        Args:
            output_dir: Directory to write generated files
            
        Returns:
            Dictionary of filename -> content
        """
        generated_files = {}

        for service_name, service in self.parser.get_all_services().items():
            # Generate stub
            stub_code = self.generate_stub(service)
            stub_file = f"{service_name.lower()}_stub.py"
            generated_files[stub_file] = stub_code

            # Generate skeleton
            skeleton_code = self.generate_skeleton(service)
            skeleton_file = f"{service_name.lower()}_skeleton.py"
            generated_files[skeleton_file] = skeleton_code

            logger.info(f"Generated {stub_file} and {skeleton_file}")

        return generated_files

    def write_files(self, generated_files: Dict[str, str], output_dir: str = ".") -> None:
        """
        Write generated files to disk.
        
        Args:
            generated_files: Dictionary of filename -> content
            output_dir: Directory to write files
        """
        os.makedirs(output_dir, exist_ok=True)

        for filename, content in generated_files.items():
            filepath = os.path.join(output_dir, filename)
            with open(filepath, 'w') as f:
                f.write(content)
            logger.info(f"Wrote {filepath}")
